# Generated by Django 2.1.1 on 2018-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vcf_file',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
