# Generated by Django 2.1.1 on 2018-12-29 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0003_post_vcf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vcf_file',
        ),
        migrations.AddField(
            model_name='patient',
            name='vcf_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
